on:
  push:
    branches:
      - 'release/*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Tag
        id: create_tag
        run: echo "::set-output name=tag_name::${GITHUB_REF##*/}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: Release ${{ steps.create_tag.outputs.tag_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Pack
        id: npm_pack
        run: |
          cp package.json ./dist
          cd ./dist
          npm pack
          echo "::set-output name=package_filename::$(ls | grep .tgz)"
      - name: Upload Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/${{ steps.npm_pack.outputs.package_filename }}
          asset_name: ${{ steps.npm_pack.outputs.package_filename }}
          asset_content_type: application/zip
